# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d7906182a7893d774ea7867dbc1841d28785610ac98f0b2f09871c420c3af9c47e43f538c7a4bc093a0386308d10d393d0f063eff2b463a2466a2c6dc46a019

test:
  secret_key_base: 75508bd3176ae58a2e36eb9e82cb45b9a2ef2029184fb82f699781c0f0c161d16cfab5351e8c08c83e962f540d75aef488a047b319f39cc73e0b65b20df42a4c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
